[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
prost = "0.9"
tokio = "1.0"
tonic = "0.6"

[build-dependencies]
tonic-build = "0.6"
